# Generated by Django 3.0.7 on 2020-08-04 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='Nazwa gry')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, verbose_name='Liga')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Poziom rozgrywkowy')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='fifarank.Game', verbose_name='Gra')),
            ],
            options={
                'ordering': ('-created', 'name', 'level'),
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=1500, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-value',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Drużyna')),
                ('rating', models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], default='3.0', max_length=3, verbose_name='Ranking')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fifarank.Game', verbose_name='Gra')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fifarank.League', verbose_name='Liga')),
            ],
            options={
                'ordering': ('-created', 'game', 'name'),
                'unique_together': {('name', 'league')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('resultHome', models.PositiveIntegerField(default=0, verbose_name='Wynik gospodarzy')),
                ('resultAway', models.PositiveIntegerField(default=0, verbose_name='Wynik gości')),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awayTeams', to='fifarank.Team', verbose_name='Drużyna gości')),
                ('awayUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awayUsers', to=settings.AUTH_USER_MODEL, verbose_name='Gość')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='fifarank.Game', verbose_name='Gra')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeTeams', to='fifarank.Team', verbose_name='Drużyna gospodarzy')),
                ('homeUser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeUsers', to=settings.AUTH_USER_MODEL, verbose_name='Gospodarz')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ('-date',),
            },
        ),
    ]
