# Generated by Django 3.0.7 on 2020-08-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifarank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='inOvertime',
            field=models.BooleanField(default=False, verbose_name='Po dogrywce'),
        ),
    ]
