# Generated by Django 3.0.7 on 2020-08-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifarank', '0002_match_inovertime'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='inPKs',
            field=models.BooleanField(default=False, verbose_name='Po rzutach karnych'),
        ),
        migrations.AddField(
            model_name='match',
            name='resultPKAway',
            field=models.PositiveIntegerField(default=0, verbose_name='Wynik gości w karnych'),
        ),
        migrations.AddField(
            model_name='match',
            name='resultPKHome',
            field=models.PositiveIntegerField(default=0, verbose_name='Wynik gospodarzy w karnych'),
        ),
    ]
