# Generated by Django 3.0.7 on 2020-07-21 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fifarank', '0002_auto_20200627_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='fifarank.Game', verbose_name='Gra'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Kod identyfikacyjny'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nazwa kraju'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=8, unique=True, verbose_name='Nazwa gry'),
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='fifarank.Country', verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='league',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='fifarank.Game', verbose_name='Gra'),
        ),
        migrations.AlterField(
            model_name='league',
            name='level',
            field=models.PositiveIntegerField(verbose_name='Poziom rozgrywkowy'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nazwa ligi'),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awayTeams', to='fifarank.Team', verbose_name='Drużyna gości'),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awayUsers', to=settings.AUTH_USER_MODEL, verbose_name='Gość'),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeTeams', to='fifarank.Team', verbose_name='Drużyna gospodarzy'),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homeUsers', to=settings.AUTH_USER_MODEL, verbose_name='Gospodarz'),
        ),
        migrations.AlterField(
            model_name='match',
            name='resultAway',
            field=models.PositiveIntegerField(verbose_name='Wynik gości'),
        ),
        migrations.AlterField(
            model_name='match',
            name='resultHome',
            field=models.PositiveIntegerField(verbose_name='Wynik gospodarzy'),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Skrót nazwy'),
        ),
        migrations.AlterField(
            model_name='team',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fifarank.Game', verbose_name='Gra'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fifarank.League', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa drużyny'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rating',
            field=models.CharField(choices=[('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5'), ('2.0', '2.0'), ('2.5', '2.5'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0')], default='3.0', max_length=3, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='userrating',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=7),
        ),
    ]
