# Generated by Django 3.0.7 on 2020-08-05 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanedBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data pożyczki')),
                ('is_given_back', models.BooleanField(default=False, verbose_name='Czy oddane')),
                ('loanee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loanees', to=settings.AUTH_USER_MODEL, verbose_name='Pożyczkobiorca')),
                ('loaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaners', to=settings.AUTH_USER_MODEL, verbose_name='Pożyczkodawca')),
            ],
        ),
    ]
