version: '3.7'

services:
  web:
    build: .
    command: gunicorn sp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/app/static
    env_file:
      - .env
    depends_on:
      - db
      
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - spdb:/var/lib/postgresql/data/
    env_file:
      - .env

  nginx:
    build: ./nginx
    volumes:
      - static:/www/static/
    ports:
      - 8000:80
    depends_on:
      - web
  
volumes:  
  spdb:
  static: