# Generated by Django 3.0.7 on 2020-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.TextField(default='Tytuł posta', max_length=100, verbose_name='Tytuł'),
            preserve_default=False,
        ),
    ]
