# Generated by Django 3.0.7 on 2020-08-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-creation_date',)},
        ),
    ]
